# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - PMAS5

on:
  pull_request:
  push: # For safety. If somehow you can push to main.
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        env:
          DEV_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DEV_USERNAME: ${{ secrets.PROD_USERNAME }}
          DEV_PASSWORD: ${{ secrets.PROD_PASSWORD }}
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Publish Test Report
        if: success()
        uses: scacap/action-surefire-report@v1


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E1FADCCB77C94EE497E66F9ECF31EE80 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04A941709D734692B4615B7260B05563 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1D6979B1B0AD41AB80ABA877D607B488 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PMAS5'
          slot-name: 'Production'
          package: '*.jar'
          